### ISSUE TITLE
Running "plax" command with no flags, tries to run a test on test.yaml file that doesn't exist

### ISSUE THREAD

**Issue by t-harwood** [Comcast/plax#33]
If you run the "plax" command without any flags or arguments, plax tries to run a -test on a test.yaml file that isn't included in the repo.

Should this command instead just print out the current Plax version?

```
$ plax
2021/02/12 11:10:12.881781 plax version 1.0.3
2021/02/12 11:10:12.882044 open /Users/tharwo200/comcast_git/plax/test.yaml: no such file or directory
```

**Comment by carlos-loya** [comment]
If a user were to run the `plax` command without any parameters or options, we should display the help menu. I think most cli tools I've used do something similar

**Comment by jsccast** [comment]
I like @carlos-loya 's suggestion -- perhaps with the addition of an actual error message like "To run a test, specify either `-test FILENAME.yaml` or `dir DIR`." That'd point the user in the right direction.  Or maybe even be more succinct:

```Shell
$ plax
error: To run a test, specify either -test FILENAME.yaml or -dir DIR. Use -h to get summary of all options.
```
