### ISSUE TITLE
Plax docker?

### ISSUE THREAD

**Issue by carlos-loya** [Comcast/plax#49]
I have been thinking about creating a Concourse resource type that would track plax/plaxrun releases, so that Concourse users could run their plax tests easily in a pipeline. However, I came across a limitation being that plax testers using a `cmd` channel to invoke system tools like `echo` or `ls` would not be able to invoke any tool outside those we include in the plax resource type docker image.

Okay, maybe a Concourse resource type isn't the way to go. So instead, how about a normal docker release image? I think again we encounter the same problem above unless plax testers build custom docker layers on top of plax using something like `FROM plax:1.x.x`, but I think it could still be considered valuable by docker users.

Any thoughts on this matter? I would love to hear different perspectives on this.

**Comment by robertfarnum** [comment]
@carlos-loya  Yes, this is a great idea, so much so that I appear to have duplicated the issue as #76 and starting working on it.  I'll close this issue and reference this issue.
