### ISSUE TITLE
Create a base Docker image with plax commands and generally useful utilities

### ISSUE THREAD

**Issue by robertfarnum** [Comcast/plax#76]

**Comment by jsccast** [comment]
Maybe close #49 as a duplicate of this issue?

**Comment by robertfarnum** [comment]
Closed #49 as duplicate of this issue. Please refer to as the original idea came from @carlos-loya

**Comment by robertfarnum** [comment]
This issue requires OSPO consideration before publishing any docker image for an open source project.  This issue is currently on hold.

**Comment by robertfarnum** [comment]
Closing this issue due to OSPO licensing issues
